const skilset = [
  "Full-Stack | ",
  "Front-End | ",
  "Back-End | ",
  "Blockchain | ",
  "Ethereum | ",
  "NFT | ",
  "Hardhat | ",
  "Remix | ",
  "Truffle | ",
  "Swift | ",
  "jQuery | ",
  "Vue | ",
  "Angular | ",
  "React | ",
  "Javascript | ",
  "CSS | ",
  "HTML | ",
  "PHP | ",
  "Python | ",
  "Ruby | ",
  "SQL | ",
  "MongoDB | ",
  "NodeJS | ",
  "Rust | ",
  "Solidity | ",
  "GoLang | ",
  "Express | ",
  "Next | ",
  "Ember | ",
  "Nuxt | ",
  "Gatsby | ",
  "GraphQL | ",
  "CSS | ",
  "Less | ",
  "Sass | ",
  "Laravel | ",
  "CI | ",
  "YII | ",
  "Drupal | ",
  "Symfony | ",
  "Django | ",
  "Flask | ",
  "FastAPI | ",
];

const keyRoles = [
  "● Brainstorm and evaluate applications for new tools and technologies ",
  "● Managed time-sensitive updates, including content changes and database upgrades.",
  "● Planned, wrote, and debugged web applications and software with complete accuracy.",
  "● Maintaining client and server-side applications.",
  "● Educating sales personnel on blockchain features that allow secure digital payments.",
  "● Documenting blockchain development processes and complying with best practices in data protection.",
  "● Optimizing and securing blockchain applications by integrating new tools and technologies.",
  "● Document and maintain new as well as existing solutions ",
  "● Creating application features and interfaces by using programming languages and writing multithreaded codes.",
  "● Applying the latest cryptology techniques to protect digital transaction data against cyberattacks and information hacks.",
  "● Developed full-stack web applications which processed, analyzed, and rendered data visually.",
  "● Designing user interactions on web pages.",
  "● Managed, optimized, and updated PHP databases as necessary.",
  "● ERC20 Token Development",
  "● Working alongside graphic designers for web design features.",
  "● Creating servers and databases for functionality.",
  "● Front-end development - React, Web3.js, Moralis",
  "● Used various ideas from distributed computing, large-scale design, real-time data processing, data storage, ML, and AI to solve challenging dataset problems.",
  "● Ensuring responsiveness of applications.",
  "● Seeing through a project from conception to finished product.",
  "● Smart Contract Development using solidity",
  "● NFT Marketplace Development",
  "● Liaised with back end developers, front end developers, quality assurance testers, and CTO as needed.",
  "● Maximized applications’ efficiency, data quality, scope, operability, and flexibility.",
  "● Keeping up with current blockchain technologies and cryptography methods.",
  "● Develop application functionality with the help of various programming languages",
  "● Meeting both technical and consumer needs.",
  "● Ensuring cross-platform optimization for mobile phones.",
  "● Designing and developing APIs.",
  "● Enterprise-grade Private blockchain solutions using Hyperledger Fabric",
  "● NFT Minting Engine - ERC721A, ERC1155",
  "● Collaborate with cross-functional teams and managers to determine blockchain technology needs",
  "● Provide security measures against various cybercrimes",
  "● Research, analyze, design, develop, test, and maintain various Blockchain applications ",
  "● Developing back end website applications.",
  "● Staying abreast of developments in web applications and programming languages.",
  "● Ethereum Decentralized Applications",
  "● Integrate new tools and technology to optimize as well as secure blockchain applications",
  "● Developed app integration with REST / SOAP and other APIs for Google Maps, social media logins, payment processors, and other services.",
  "● Design, implement, and support distributed blockchain-based network",
  "● Connect with key stakeholders, technical partners, developers community and discuss innovative ideas ",
  "● Support and maintain current as well as future distributed applications ",
  "● Back-end Development - Node.js, GraphQL",
  "● Developing front end website architecture.",
  "● Collaborating with managers to determine blockchain technology needs and envisaged functionalities.",
  "● Working alongside Front-End Developers to develop high quality user-facing elements",
  "● Ensuring applications are optimised for speed and convenience, and making sure existing platforms can be scaled up in the future",
  "● Incorporating adequate and future-proof security elements and monitoring their continuing practicality",
  "● Implementing data storage applications and maintaining their effectiveness",
  "● Working with senior management to make sure the user experience continues to be of a high standard",
  "● Collaborating with relevant team members at all stages of the relevant processes",
  "● Hands-on experience in developing user interface applications with JavaScript, HTML5, CSS3 and Bootstrap.",
  "● Hands-on experience in developing secure and scalable web applications using at least one of the following frameworks/libraries - React/Angular/Vue/ DOM/BOM/Ajax/JSON/jQuery.",
  "● Hand-on experience in developing high-performance, reusable code for Web application.",
  "● English communication capability",
];

const companies = [
  { name: "Quytech", city: "NYC", country: "United States", },
  { name: "OpenXcell", city: "Sunnyvale", country: "United States", },
  { name: "Alphonic Network Solutions Pvt. Ltd.", city: "Chicago", country: "United States", },
  { name: "InterScale", city: "Washington DC", country: "United States", },
  { name: "Hash Code Programmers Private Limited", city: "Ashburn", country: "United States", },
  { name: "Blocktech", city: "NYC", country: "United States", },
  { name: "Cryptonomex Inc.", city: "Blacksburg", country: "United States", },
  { name: "MixBytes", city: "San Francisco", country: "United States", },
  { name: "Deqode", city: "Wilmington", country: "United States", },
  { name: "Suffescom Solutions Inc", city: "California City", country: "United States", },
  { name: "Bitdeal", city: "McAllen", country: "United States", },
  { name: "TechGropse Pvt. Ltd.", city: "Decatur", country: "United States", },
  { name: "Antier Solutions", city: "San Jose", country: "United States", },
  { name: "CDN Solutions Group", city: "Phoenix", country: "United States", },
  { name: "HoC Solutions", city: "Providence", country: "United States", },

  { name: "Peiko", city: "Kyiv", country: "Ukraine", },
  { name: "Altamira", city: "Kyiv", country: "Ukraine", },
  { name: "OpenGeeksLab", city: "Zaporizhia", country: "Ukraine", },
  { name: "TrendLine Global", city: "Kyiv", country: "Ukraine", },
  { name: "Redwerk", city: "Kyiv", country: "Ukraine", },
  { name: "Cleveroad", city: "Dnipropetrovsk", country: "Ukraine", },
  { name: "JustCoded", city: "Kharkiv", country: "Ukraine", },
  { name: "OTAKOYI", city: "Lviv", country: "Ukraine", },
  { name: "Relevant Software", city: "Lviv", country: "Ukraine", },
  { name: "VT Labs", city: "Kyiv", country: "Ukraine", },
  { name: "Artelogic", city: "Lviv", country: "Ukraine", },
  { name: "MobiDev", city: "Chernivtsi", country: "Ukraine", },
  { name: "Unit Space", city: "Kharkiv", country: "Ukraine", },
  { name: "SamsonOS", city: "Kyiv", country: "Ukraine", },
  { name: "Web Peppers", city: "Kyiv", country: "Ukraine", },


  { name: "7EDGE", city: "Melbourne", country: "Australia", },
  { name: "Zealous System", city: "Melbourne", country: "Australia", },
  { name: "Bachoo", city: "Melbourne", country: "Australia", },
  { name: "PageTraffic Inc", city: "Sydney", country: "Australia", },
  { name: "GlanceSys Information Technology Private Limited", city: "Sydney", country: "Australia", },
  { name: "Promatics Technologies", city: "Sydney", country: "Australia", },
  { name: "KrishaWeb", city: "Melbourne", country: "Australia", },
  { name: "Next Big Technology(NBT)", city: "Sydney", country: "Australia", },
  { name: "Dedicated Developers", city: "Sydney", country: "Australia", },
  { name: "Caveni Digital Solutions", city: "Sydney", country: "Australia", },
  { name: "Vrinsoft Technology", city: "Melbourne", country: "Australia", },
  { name: "Codiant Software Technologies Pvt. Ltd.", city: "Sydney", country: "Australia", },
  { name: "Ateam Soft Solutions", city: "Gold Coast", country: "Australia", },
  { name: "Web Design Sun®", city: "Sydney", country: "Australia", },
  { name: "SAG IPL", city: "Lalor", country: "Australia", },

  { name: "7EDGE", city: "Bengaluru", country: "India", },
  { name: "SPEC INDIA", city: "Ahmedabad", country: "India", },
  { name: "OpenXcell", city: "Ahmedabad", country: "India", },
  { name: "AllianceTek", city: "Ahmedabad", country: "India", },
  { name: "Zealous System", city: "Ahmedabad", country: "India", },
  { name: "Brights", city: "Ahmedabad", country: "India", },
  { name: "Binmile Technologies", city: "Mumbai", country: "India", },
  { name: "Alphonic Network Solutions Pvt. Ltd.", city: "Jaipur", country: "India", },
  { name: "PageTraffic Inc", city: "Delhi", country: "India", },
  { name: "Aalpha Information Systems India Pvt. Ltd.", city: "Hubli", country: "India", },
  { name: "Promatics Technologies", city: "Ludhiana", country: "India", },
  { name: "GlanceSys Information Technology Private Limited", city: "Gwalior", country: "India", },
  { name: "Next Big Technology(NBT)", city: "Jaipur", country: "India", },
  { name: "Dynamic Dreamz", city: "Surat", country: "India", },
  { name: "BrancoSoft Private Limited", city: "Noida", country: "India", },

  { name: "Magneto IT Solutions", city: "London", country: "United Kingdom", },
  { name: "7EDGE", city: "London", country: "United Kingdom", },
  { name: "SPEC INDIA", city: "London", country: "United Kingdom", },
  { name: "Powercode", city: "London", country: "United Kingdom", },
  { name: "AllianceTek", city: "London", country: "United Kingdom", },
  { name: "Glorium Technologies", city: "London", country: "United Kingdom", },
  { name: "Zealous System", city: "London", country: "United Kingdom", },
  { name: "Brights", city: "London", country: "United Kingdom", },
  { name: "CodeBright", city: "London", country: "United Kingdom", },
  { name: "instinctools", city: "London", country: "United Kingdom", },
  { name: "Bachoo", city: "London", country: "United Kingdom", },
  { name: "Dedicated Developers", city: "London", country: "United Kingdom", },
  { name: "Gearheart", city: "London", country: "United Kingdom", },
  { name: "LinkUp Studio", city: "London", country: "United Kingdom", },
  { name: "HQSoftware", city: "London", country: "United Kingdom", },
  
  // { name: "FlyNaut LLC", city: "Ardon", country: "Russia", },
  // { name: "Burning Buttons LLC", city: "Omsk", country: "Russia", },
  // { name: "Exceed Team", city: "Taganrog", country: "Russia", },
  // { name: "4xxi", city: "Sankt Peterburg", country: "Russia", },
  // { name: "Digital Skynet", city: "Taganrog", country: "Russia", },
  // { name: "HWdTech", city: "Omsk", country: "Russia", },
  // { name: "2V Modules", city: "Moscow", country: "Russia", },
  // { name: "ADCI Solutions", city: "Omsk", country: "Russia", },
  // { name: "NetLabCS", city: "Moscow", country: "Russia", },
  // { name: "Axmit", city: "Petrozavodsk", country: "Russia", },
  // { name: "INOSTUDIO", city: "Taganrog", country: "Russia", },
  // { name: "CimpleO", city: "Omsk", country: "Russia", },
  // { name: "fructus temporum", city: "Moscow", country: "Russia", },
  // { name: "Zimalab", city: "Novosibirsk", country: "Russia", },
  // { name: "RentaTeam", city: "Moscow", country: "Russia", },


  // { name: "Smart IT", city: "Minsk", country: "Belarus", },
  // { name: "Axora", city: "Minsk", country: "Belarus", },
  // { name: "SaM Solutions", city: "Minsk", country: "Belarus", },
  // { name: "UNL Solutions", city: "Minsk", country: "Belarus", },
  // { name: "Right Studio", city: "Minsk", country: "Belarus", },
  // { name: "Adexin", city: "Minsk", country: "Belarus", },
  // { name: "Arateg", city: "Minsk", country: "Belarus", },
  // { name: "J Lab LLC", city: "Minsk", country: "Belarus", },
  // { name: "MastakStudio", city: "Minsk", country: "Belarus", },
  // { name: "CleverLabs", city: "Minsk", country: "Belarus", },
  // { name: "Magedia", city: "Minsk", country: "Belarus", },
  // { name: "Scand", city: "Minsk", country: "Belarus", },
  // { name: "Fresh Lemon Soft", city: "Minsk", country: "Belarus", },
  // { name: "LOVATA", city: "Minsk", country: "Belarus", },
  // { name: "SmartApp", city: "Minsk", country: "Belarus", },


  { name: "Magneto IT Solutions", city: "Toronto", country: "Canada", },
  { name: "7EDGE", city: "Calgary", country: "Canada", },
  { name: "SPEC INDIA", city: "Toronto", country: "Canada", },
  { name: "OpenXcell", city: "Toronto", country: "Canada", },
  { name: "Powercode", city: "Toronto", country: "Canada", },
  { name: "AllianceTek", city: "Toronto", country: "Canada", },
  { name: "Glorium Technologies", city: "Toronto", country: "Canada", },
  { name: "Zealous System", city: "Montreal", country: "Canada", },
  { name: "Brights", city: "Toronto", country: "Canada", },
  { name: "CodeBright", city: "Toronto", country: "Canada", },
  { name: "instinctools", city: "Toronto", country: "Canada", },
  { name: "Bachoo", city: "Toronto", country: "Canada", },
  { name: "Dedicated Developers", city: "Victoria", country: "Canada", },
  { name: "Gearheart", city: "Toronto", country: "Canada", },
  { name: "Canada", city: "Toronto", country: "Canada", },
  
  { name: "SolveIt", city: "Tallinn", country: "Estonia", },
  { name: "Design Den", city: "Tallinn", country: "Estonia", },
  { name: "Axmit", city: "Tallinn", country: "Estonia", },
  { name: "Swaran Soft Support Solutions Pvt. Ltd.", city: "Tallinn", country: "Estonia", },
  { name: "Impulsis", city: "Tallinn", country: "Estonia", },
  { name: "Bamboo Agile", city: "Tallinn", country: "Estonia", },
  { name: "Perpetio", city: "Tallinn", country: "Estonia", },
  { name: "8allocate", city: "Tallinn", country: "Estonia", },
  { name: "Qubit Labs", city: "Tallinn", country: "Estonia", },
  { name: "Carter Point", city: "Tallinn", country: "Estonia", },
  { name: "Limegrow Web Development", city: "Tallinn", country: "Estonia", },
  { name: "Decima Digital", city: "Tallinn", country: "Estonia", },
  { name: "Techstack Ltd", city: "Tallinn", country: "Estonia", },
  { name: "Brainbean Apps", city: "Tallinn", country: "Estonia", },
  { name: "Code Care", city: "Tallinn", country: "Estonia", },
  
]

const roles = [
  "Senior Software Engineer",
  "Software Engineer",
  "Senior Full Stack Developer",
  "Full Stack Developer",
  "Senior Full Stack Engineer",
  "Full Stack Engineer",
  "Senior Front End Engineer",
  "Front End Engineer",
  "Senior Back End Engineer",
  "Back End Engineer",
  "Senior Blockchain Engineer",
  "Blockchain Engineer",
  "Senior Blockchain Developer",
  "Blockchain Developer",
  "Senior Defi/Dapp/Dex Developer",
  "Blockchain Front-End Developer",
  "Blockchain Back-End Developer",
]

module.exports = {
  roles,
  companies,
  skilset,
  keyRoles,
};
